version: '3.9'

services:

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./dev/urandom:/dev/random:ro
    ports:
      - "8203:3000"
    restart: unless-stopped 
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: User
      MB_DB_PASS: p4ssw0rd
      MB_DB_HOST: postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped 
    environment:
      POSTGRES_USER: User
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: p4ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1  
    restart: unless-stopped  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - "8201:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-1
    ports: 
      - "8205:8080"
    restart: unless-stopped 
    volumes: 
      - ./noco.db:/usr/app/data/noco.db

volumes: 
  pgadmin:

